### PR TITLE
Added C# 9 record handling

### PR DESCRIPTION
**Pull request by bigtlb**
C# 9 `record` type should work similar to `class` but it has some built in members and a specific inheritance, which may be better off hidden.

- Added a test for `IsRecord` And `TypeKind.Record`  updated  generation code to output `record` in place of `class`, but also consider record inn most places where classes are considered (although it can't inherit).
- Added in a helper method to determine if a member of a record is one of the builtin methods (Clone, ToString, Deconstruct, Equals, etc.).
- Also cleaned up blocks with unnecesary `elses` 
```csharp
if (...)
  return;
else if (...)
  return;
else if (...)
  return;
```
 can be
```csharp
if (...)
  return;
if (...)
  return;
if (...)
  return;
```

Suggested next steps is hide `IEquatable<T>` inheritance and builtin members.

image

### CODE REVIEW

**Comment by ejball** [comment]
Thanks for the contribution! I agree that hiding `IEquatable<T>` and the synthesized members makes sense, except for the public properties.

**Comment by bigtlb** [comment]
Please advise on how I can make the build succeed.

**Comment by ejball** [comment]
Looks like XML documentation comments [didn't work correctly with records](https://stackoverflow.com/a/64681327/23818) under 5.0.100. I've changed GitHub Actions to use the latest .NET 5 SDK; perhaps merging that in that will fix the PR build.

**Comment by ejball** [comment]
You should also run `.\build.ps1 generate-docs` and commit those changes.

**Comment by bigtlb** [comment]
Thanks. I was just noticing that part.

**Comment by bigtlb** [comment]
Should be good now.  it build on my branch.

**Comment by ejball** [comment]
Rebased and amended: #121. Thanks again!

**Pull request closed without merging**
